# Generated by Django 6.0.1 on 2026-03-04 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0001_initial"),
        ("vehicle", "0002_technicalinspection_created_by_vehicle_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicleownerhistory",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="vehicleownerhistory",
            name="driver",
        ),
        migrations.RemoveField(
            model_name="vehicleownerhistory",
            name="vehicle",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="driver",
        ),
        migrations.CreateModel(
            name="OwnerHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreement_number", models.CharField(blank=True, max_length=100)),
                ("assigned_at", models.DateTimeField()),
                ("unassigned_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ownership_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="past_vehicles",
                        to="driver.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_history",
                        to="vehicle.vehicle",
                    ),
                ),
            ],
            options={
                "ordering": ["-unassigned_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleOwner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreement_number", models.CharField(blank=True, max_length=100)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_vehicle_owners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_vehicles",
                        to="driver.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="current_owner",
                        to="vehicle.vehicle",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="VehicleDriverHistory",
        ),
        migrations.DeleteModel(
            name="VehicleOwnerHistory",
        ),
    ]
