# Generated by Django 6.0.1 on 2026-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0003_remove_vehicleownerhistory_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[
                    ("AUCTION", "Auction Selection"),
                    ("FOCUS", "Focus"),
                    ("GAS_INSTALL", "Gas Installation"),
                    ("SERVICE", "Service"),
                    ("CLEANING", "Cleaning"),
                    ("PRE_DELIVERY", "Pre-delivery"),
                    ("READY", "Ready for Delivery"),
                    ("RENT", "Rent"),
                    ("LEASING", "Leasing"),
                    ("SELLING", "Report for Sale"),
                    ("SOLD", "Sold"),
                ],
                default="AUCTION",
                max_length=20,
            ),
        ),
    ]
