# Generated by Django 6.0.1 on 2026-03-05 08:58

import vehicle.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0004_update_vehicle_status_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclephoto",
            name="image",
            field=models.ImageField(upload_to=vehicle.models.vehicle_photo_path),
        ),
    ]
