# Generated by Django 5.2.12 on 2026-03-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_fuel_type_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_temporary_plate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='car_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
