# Generated by Django 5.2.12 on 2026-03-11 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_vehicle_idx_status_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['-updated_at'], name='idx_vehicle_updated_at'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['is_archived', '-updated_at'], name='idx_vehicle_archived_updated'),
        ),
    ]
