# Generated by Django 6.0.1 on 2026-03-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0009_vehicle_fuel_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="technicalinspection",
            name="next_inspection_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
