# Generated by Django 6.0.1 on 2026-03-03 10:25

from django.db import migrations


def backfill_next_inspection_date(apps, schema_editor):
    TechnicalInspection = apps.get_model("vehicle", "TechnicalInspection")
    for ins in TechnicalInspection.objects.filter(next_inspection_date__isnull=True):
        d = ins.inspection_date
        try:
            ins.next_inspection_date = d.replace(year=d.year + 1)
        except ValueError:
            ins.next_inspection_date = d.replace(year=d.year + 1, day=28)
        ins.save(update_fields=["next_inspection_date"])


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_technicalinspection_next_inspection_date'),
    ]

    operations = [
        migrations.RunPython(backfill_next_inspection_date, migrations.RunPython.noop),
    ]
