# Generated by Django 5.2.12 on 2026-03-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0010_vehicle_year_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="manufacturer",
            field=models.CharField(
                choices=[
                    ("Toyota", "Toyota"),
                    ("Ford", "Ford"),
                    ("Honda", "Honda"),
                    ("Chevrolet", "Chevrolet"),
                    ("BMW", "BMW"),
                    ("Lexus", "Lexus"),
                    ("Audi", "Audi"),
                    ("Tesla", "Tesla"),
                ],
                max_length=50,
            ),
        ),
    ]
