# Generated by Django 5.2.12 on 2026-03-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicle", "0013_vehiclephoto_is_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GASOLINE", "Gasoline"),
                    ("DIESEL", "Diesel"),
                    ("LPG", "LPG"),
                    ("LPG_GASOLINE", "LPG + Gasoline"),
                    ("ELECTRIC", "Electric"),
                    ("HYBRID", "Hybrid"),
                    ("GAS_GASOLINE_HYBRID", "Gas + Gasoline + Hybrid"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
