# Generated by Django 6.0.1 on 2026-02-17 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fleet_management", "0001_initial"),
        ("vehicle", "0002_alter_vehicle_status_delete_vehiclestatus"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FleetVehicleRegulationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("every_km", models.PositiveIntegerField()),
                ("notify_before_km", models.PositiveIntegerField(default=500)),
            ],
        ),
        migrations.RenameField(
            model_name="fleetvehicleregulation",
            old_name="created_at",
            new_name="assigned_at",
        ),
        migrations.CreateModel(
            name="FleetVehicleRegulationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_done_km", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "regulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="fleet_management.fleetvehicleregulation",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="fleet_management.fleetvehicleregulationitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("regulation", "item")},
            },
        ),
        migrations.CreateModel(
            name="FleetVehicleRegulationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("performed", "Service Performed"),
                            ("km_updated", "KM Updated"),
                            ("notified", "Notification Sent"),
                        ],
                        max_length=20,
                    ),
                ),
                ("km_at_event", models.PositiveIntegerField()),
                ("km_remaining", models.IntegerField()),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="regulation_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="fleet_management.fleetvehicleregulationentry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FleetVehicleRegulationSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_regulation_schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fleetvehicleregulationitem",
            name="schema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="fleet_management.fleetvehicleregulationschema",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fleetvehicleregulation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="fleetvehicleregulation",
            name="schema",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="regulations",
                to="fleet_management.fleetvehicleregulationschema",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="fleetvehicleregulation",
            unique_together={("schema", "vehicle")},
        ),
        migrations.AlterUniqueTogether(
            name="fleetvehicleregulationitem",
            unique_together={("schema", "title")},
        ),
        migrations.RemoveField(
            model_name="fleetvehicleregulation",
            name="regulation_json",
        ),
        migrations.RemoveField(
            model_name="fleetvehicleregulation",
            name="updated_at",
        ),
    ]
