# Generated by Django 6.0.1 on 2026-02-27 21:04

from django.db import migrations, models


def deduplicate_schema_titles(apps, schema_editor):
    """Keep the first (lowest pk) schema for each title, delete the rest."""
    FleetVehicleRegulationSchema = apps.get_model("fleet_management", "FleetVehicleRegulationSchema")
    seen = {}
    for schema in FleetVehicleRegulationSchema.objects.order_by("id"):
        if schema.title in seen:
            schema.delete()
        else:
            seen[schema.title] = schema.pk


class Migration(migrations.Migration):
    # RunPython (DELETE) + AlterField (DDL) can't run in the same transaction
    # on PostgreSQL due to pending trigger events — run each op non-atomically.
    atomic = False

    dependencies = [
        ('fleet_management', '0006_seed_default_regulation_schema'),
    ]

    operations = [
        migrations.RunPython(deduplicate_schema_titles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='fleetvehicleregulationschema',
            name='title',
            field=models.CharField(max_length=155, unique=True),
        ),
    ]
