# Generated by Django 6.0.1 on 2026-03-01 12:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("driver", "0001_initial"),
        ("vehicle", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="System slug (FUEL, SERVICE …). Null for custom categories.",
                        max_length=30,
                        null=True,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, max_length=50)),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Hex color, e.g. #F59E0B",
                        max_length=7,
                    ),
                ),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Expense Category",
                "verbose_name_plural": "Expense Categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("expense_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="expenses/receipts/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="vehicle.vehicle",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="expense.expensecategory",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["vehicle", "category"],
                name="expense_exp_vehicle_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["expense_date"],
                name="expense_exp_expense_idx",
            ),
        ),
        migrations.CreateModel(
            name="FuelExpenseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "liters",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "price_per_liter",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("GASOLINE", "Gasoline"),
                            ("DIESEL", "Diesel"),
                            ("LPG", "LPG"),
                            ("ELECTRIC", "Electric"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gas_station",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "odometer_km",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fuel_detail",
                        to="expense.expense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fuel detail",
            },
        ),
        migrations.CreateModel(
            name="ServiceExpenseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_type", models.CharField(max_length=100)),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "workshop_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "odometer_km",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_detail",
                        to="expense.expense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service detail",
            },
        ),
        migrations.CreateModel(
            name="InsuranceExpenseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_number", models.CharField(max_length=100)),
                ("insurance_company", models.CharField(max_length=100)),
                ("coverage_start", models.DateField()),
                ("coverage_end", models.DateField()),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_detail",
                        to="expense.expense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insurance detail",
            },
        ),
        migrations.CreateModel(
            name="WashingExpenseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wash_type",
                    models.CharField(
                        choices=[
                            ("EXTERIOR", "Exterior"),
                            ("INTERIOR", "Interior"),
                            ("FULL", "Full"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="washing_detail",
                        to="expense.expense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Washing detail",
            },
        ),
        migrations.CreateModel(
            name="FineExpenseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fine_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("violation_type", models.CharField(max_length=100)),
                ("fine_date", models.DateField(blank=True, null=True)),
                (
                    "driver_at_time",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fines",
                        to="driver.driver",
                    ),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fine_detail",
                        to="expense.expense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fine detail",
            },
        ),
        migrations.CreateModel(
            name="ExpensePart",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("product_url", models.URLField(blank=True)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "unit_price",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts",
                        to="expense.expense",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ExpenseInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="expenses/invoices/"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="expense.expense",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
