# Generated by Django 6.0.1 on 2026-03-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0002_seed_default_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="expense_date",
            field=models.DateTimeField(),
        ),
    ]
