# Generated by Django 6.0.1 on 2026-03-05 12:44

import django.db.models.deletion
import expense.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0004_reorder_category_priorities"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "number",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="expenses/invoices/",
                        validators=[expense.models.validate_invoice_file],
                    ),
                ),
                ("vendor_name", models.CharField(blank=True, max_length=200)),
                ("invoice_date", models.DateField(blank=True, null=True)),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="expense.invoice",
            ),
        ),
        migrations.DeleteModel(
            name="ExpenseInvoice",
        ),
    ]
