# Generated by Django 5.2.12 on 2026-03-11 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("driver", "0001_initial"),
        ("expense", "0005_invoice_expense_invoice_delete_expenseinvoice"),
        ("vehicle", "0011_add_company_client_amounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="approval_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DRAFT", "Draft"),
                    ("SENT", "Sent"),
                    ("REVIEW", "Review"),
                    ("APPROVED", "Approved"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="client_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="client_driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="client_expenses",
                to="driver.driver",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="company_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["approval_status"], name="expense_exp_approva_0dbaa4_idx"
            ),
        ),
    ]
