# Generated by Django 6.0.1 on 2026-03-01 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0005_inspection"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="expense",
            new_name="expense_exp_vehicle_9bc038_idx",
            old_name="expense_exp_vehicle_idx",
        ),
        migrations.RenameIndex(
            model_name="expense",
            new_name="expense_exp_expense_46ea33_idx",
            old_name="expense_exp_expense_idx",
        ),
    ]
