# Generated by Django 6.0.1 on 2026-03-03 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0007_remove_expense_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expensepart",
            name="product_url",
        ),
        migrations.AddField(
            model_name="expense",
            name="expense_for",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="expense",
            name="payer_type",
            field=models.CharField(
                choices=[("COMPANY", "Company"), ("CLIENT", "Client")],
                default="COMPANY",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="payment_method",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("CASHLESS", "Cashless")],
                default="CASHLESS",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PartsExpenseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_name", models.CharField(blank=True, max_length=200)),
                (
                    "supplier_type",
                    models.CharField(
                        choices=[
                            ("DISASSEMBLY", "Disassembly"),
                            ("INDIVIDUAL", "Individual"),
                        ],
                        default="DISASSEMBLY",
                        max_length=20,
                    ),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parts_detail",
                        to="expense.expense",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parts detail",
            },
        ),
    ]
