# Generated by Django 5.2.12 on 2026-03-12 11:30

import expense.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0008_remove_amount_use_company_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, upload_to='expenses/invoices/', validators=[expense.models.validate_invoice_file]),
        ),
    ]
