# Generated by Django 5.2.12 on 2026-03-12 12:14

from django.db import migrations


def populate_amount(apps, schema_editor):
    """Copy company_amount + coalesce(client_amount, 0) → amount for every existing expense."""
    Expense = apps.get_model("expense", "Expense")
    for exp in Expense.objects.all().iterator(chunk_size=500):
        exp.amount = (exp.company_amount or 0) + (exp.client_amount or 0)
        # For COMPANY payer: clear company_amount (amount is the primary field now)
        if exp.payer_type == "COMPANY":
            exp.company_amount = None
        exp.save(update_fields=["amount", "company_amount"])


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0010_restore_amount_field"),
    ]

    operations = [
        migrations.RunPython(populate_amount, migrations.RunPython.noop),
    ]
