# Generated by Django 6.0.1 on 2026-03-03 16:57

import expense.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0010_accessories_documents_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseinvoice',
            name='file',
            field=models.FileField(upload_to=expense.models.invoice_upload_to, validators=[expense.models.validate_invoice_file]),
        ),
    ]
